# Generated by Django 4.2.16 on 2025-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateField(),
        ),
    ]
