# Generated by Django 4.2.16 on 2025-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_carouselimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
