# Generated by Django 4.2.20 on 2025-04-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='It is in 24-hour format'),
        ),
    ]
