# Generated by Django 4.2.16 on 2025-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name of Sponsor (Organization and/or Individual)', max_length=125, unique=True)),
                ('website', models.URLField(blank=True, help_text="Enter link to organization's website", verbose_name='Website Link')),
                ('image', models.ImageField(help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
            ],
        ),
    ]
