# Generated by Django 4.2.16 on 2025-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACMKekuhaupioCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.CharField(help_text='Please enter sememster that they participated in. E.g Fall 2024', max_length=20)),
                ('accomplishments', models.TextField(help_text='Summary of what they achieved in the program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Reflections or notes goes here')),
                ('image', models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
            ],
            options={
                'verbose_name': 'ACM Kekuhaupio Cohort',
            },
        ),
    ]
