# Generated by Django 4.2.20 on 2025-05-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_acmkekuhaupiocohort'),
        ('website', '0008_sponsor'),
    ]

    operations = [
    ]
