# Generated by Django 4.2.20 on 2025-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_merge_0008_acmkekuhaupiocohort_0008_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
                ('bio', models.CharField(help_text='(optional) Enter a short biography or background description about faculty member.', max_length=200)),
            ],
        ),
    ]
