# Generated by Django 4.2.16 on 2025-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='bio',
            field=models.CharField(blank=True, help_text='(optional) Enter a short biography or background description about faculty member.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype'),
        ),
    ]
