# Generated by Django 4.2.16 on 2025-05-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_leadership_bio_alter_leadership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(choices=[('1', 'President'), ('2', 'Vice President'), ('3', 'Secretary'), ('4', 'Treasurer'), ('5', 'Advisor')], max_length=50),
        ),
    ]
