# Generated by Django 4.2.16 on 2025-05-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_leadership_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(choices=[('1', 'President'), ('2', 'Vice President'), ('3', 'Director of Membership'), ('4', 'Operations Director'), ('5', 'Public Relations Director'), ('6', 'Finance Coordinator'), ('7', 'Operations Coordinator'), ('8', 'Marketing Manager'), ('9', 'Server Administrator & Webmaster'), ('10', 'Faculty Sponsor')], max_length=50),
        ),
    ]
