# Generated by Django 4.2.16 on 2025-05-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_leadership_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Leadership', 'verbose_name_plural': 'Leadership'},
        ),
    ]
