# Generated by Django 4.2.16 on 2025-06-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_leadership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question that is asked frequently', max_length=100, unique=True)),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
