# Generated by Django 4.2.16 on 2025-06-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'F.A.Q'},
        ),
    ]
