# Generated by Django 4.2.16 on 2025-06-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_faq_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='link_url',
            new_name='website',
        ),
        migrations.AddField(
            model_name='program',
            name='about',
            field=models.TextField(blank=True, help_text='Description or overview of program'),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='link_name',
            field=models.CharField(blank=True, help_text='Short label for the URL, e.g "Visit Site"', max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Name of Club/Program', max_length=175, unique=True),
        ),
        migrations.CreateModel(
            name='ProgramLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=90)),
                ('logo', models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.program')),
            ],
        ),
    ]
