# Generated by Django 4.2.16 on 2025-06-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_link_url_program_website_program_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programleadership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.program'),
        ),
    ]
