# Generated by Django 4.2.16 on 2025-06-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_programleadership_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programleadership',
            options={'verbose_name_plural': 'Program Leadership'},
        ),
    ]
