# Generated by Django 4.2.20 on 2025-08-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_programleadership_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programleadership',
            old_name='logo',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='program',
            name='link_name',
        ),
        migrations.AlterField(
            model_name='program',
            name='about',
            field=models.TextField(help_text='Description or overview of program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='website',
            field=models.URLField(blank=True, help_text='Enter full link to the external club/program website'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, default='website/handshake.png', help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype'),
        ),
    ]
