# Generated by Django 4.2.16 on 2025-08-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_logo_programleadership_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
    ]
