# Generated by Django 4.2.16 on 2025-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_sponsor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype'),
        ),
    ]
