# Generated by Django 4.2.16 on 2025-08-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_sponsor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='details',
        ),
    ]
