# Generated by Django 4.2.16 on 2025-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_sponsor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='details',
            field=models.TextField(blank=True, default='', help_text='details of the sponsor', null=True),
        ),
    ]
