# Generated by Django 4.2.16 on 2025-08-16 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_sponsor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Details of the sponsor (max 250 characters)', null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
