# Generated by Django 4.2.22 on 2025-09-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_sponsor_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of SIG', max_length=175, unique=True)),
                ('logo', models.ImageField(help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
                ('slug', models.SlugField(default='', unique=True)),
                ('about', models.TextField(blank=True, help_text='Description or overview of SIG')),
                ('website', models.URLField(blank=True, help_text='Enter full link to the SIG website')),
                ('link_name', models.CharField(blank=True, help_text='Short label for the URL, e.g "Visit Site"', max_length=150)),
            ],
            options={
                'verbose_name': 'SIG',
                'verbose_name_plural': 'SIGS',
            },
        ),
        migrations.CreateModel(
            name='SIGSLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=90)),
                ('logo', models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype')),
                ('sigs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sigs')),
            ],
            options={
                'verbose_name': 'SIGS Leadership',
                'verbose_name_plural': 'SIGS Leadership',
            },
        ),
        migrations.RemoveField(
            model_name='programleadership',
            name='program',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramLeadership',
        ),
    ]
