# Generated by Django 4.2.22 on 2025-09-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_sponsor_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='SIGS'
        ),
        migrations.AddField(
            model_name='SIGS',
            name='link_name',
            field=models.CharField(blank=True, help_text='Short label for the URL, e.g "Visit Site"', max_length=150),
        ),
        migrations.AlterField(
            model_name='SIGS',
            name='name',
            field=models.CharField(help_text='Name of SIG', max_length=175, unique=True)
        ),
        migrations.AlterField(
            model_name='SIGS',
            name='about',
            field=models.TextField(blank=True, help_text='Description or overview of SIG')
        ),
        migrations.AlterField(
            model_name='SIGS',
            name='website',
            field=models.URLField(blank=True, help_text='Enter full link to the SIG website')
        ),
        migrations.AlterModelOptions(
            name='SIGS',
            options={
                'verbose_name':'SIG',
                'verbose_name_plural':'SIGS'
            }
        ),
        migrations.RenameModel(
            old_name='ProgramLeadership',
            new_name='SIGSLeadership'
        ),
        migrations.RenameField(
            model_name='SIGSLeadership',
            old_name='program',
            new_name='sigs'
        ),
        migrations.AlterField(
            model_name='SIGSLeadership',
            name='sigs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sigs')
        ),
        migrations.AlterModelOptions(
            name='SIGSLeadership',
            options={
                'verbose_name':'SIGS Leadership', 
                'verbose_name_plural':'SIGS Leadership'
            }
        ),
    ]
