# Generated by Django 4.2.24 on 2025-09-26 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_sigs_sigsleadership_remove_programleadership_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigs',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Primary color for this SIG (hex color code, e.g., #3B82F6 for blue)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #3B82F6)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
