# Generated by Django 4.2.24 on 2025-10-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_sigs_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(choices=[('1', 'President'), ('2', 'Vice President'), ('3', 'Operations Director'), ('4', 'Finance Director'), ('5', 'Public Relations Director'), ('6', 'Webmaster'), ('7', 'Director of Membership'), ('8', 'Faculty Sponsor')], max_length=50),
        ),
    ]
