# Generated by Django 4.2.24 on 2025-10-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_leadership_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the event will take place', max_length=255),
        ),
    ]
