# Generated by Django 4.2.24 on 2025-10-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly version of the title', unique=True),
        ),
    ]
