# Generated by Django 4.2.24 on 2025-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigs',
            name='discord_link',
            field=models.URLField(blank=True, help_text='Discord server invite link (optional)'),
        ),
        migrations.AddField(
            model_name='sigs',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub organization/repository link (optional)'),
        ),
        migrations.AddField(
            model_name='sigs',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram profile link (optional)'),
        ),
        migrations.AddField(
            model_name='sigs',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='LinkedIn page link (optional)'),
        ),
    ]
