# Generated by Django 4.2.24 on 2025-10-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_sigs_discord_link_sigs_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(blank=True, help_text='\n        Please compress the image and convert type to webp before uploading.\n        https://imagecompressor.com,\n        https://cloudconvert.com/webp-converter\n        ', null=True, upload_to='website.File/bytes/filename/mimetype'),
        ),
    ]
