# Generated by Django 4.2.24 on 2025-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_leadership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigs',
            name='meeting_days',
            field=models.CharField(blank=True, help_text='Meeting days (e.g., Monday-Friday, Tuesday & Thursday, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='sigs',
            name='meeting_end_time',
            field=models.TimeField(blank=True, help_text='Meeting end time (24-hour format)', null=True),
        ),
        migrations.AddField(
            model_name='sigs',
            name='meeting_location',
            field=models.CharField(blank=True, help_text='Meeting location (e.g., POST 318B, Online, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='sigs',
            name='meeting_start_time',
            field=models.TimeField(blank=True, help_text='Meeting start time (24-hour format)', null=True),
        ),
    ]
