# Generated by Django 4.2.24 on 2025-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_sigs_meeting_days_sigs_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigs',
            name='meeting_days',
            field=models.CharField(blank=True, choices=[('', 'Select a day'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday-Friday', 'Monday-Friday'), ('Monday-Thursday', 'Monday-Thursday'), ('Tuesday-Thursday', 'Tuesday-Thursday'), ('Weekends', 'Weekends (Saturday-Sunday)'), ('Daily', 'Daily'), ('TBD', 'To Be Determined')], help_text='Select the meeting days for this SIG', max_length=20),
        ),
    ]
