# Generated by Django 4.2.24 on 2025-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_sigs_meeting_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigs',
            name='meeting_days',
            field=models.CharField(blank=True, choices=[('', 'Select a day'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Select the meeting days for this SIG', max_length=20),
        ),
    ]
