# Generated by Django 4.2.25 on 2026-06-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_sigs_meeting_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('social', 'Social'), ('talk', 'Talk'), ('hackathon', 'Hackathon'), ('networking', 'Networking'), ('competition', 'Competition'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', help_text='Type of event', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='sig',
            field=models.ForeignKey(blank=True, help_text='SIG hosting this event. Leave blank for general ACM events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.sigs'),
        ),
    ]
