# Generated by Django 4.2.30 on 2026-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_event_kind_event_sig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigs',
            name='expanded_name',
            field=models.CharField(blank=True, help_text='Optional full name under the title, e.g "Programs and Algorithms"', max_length=200),
        ),
    ]
